### ISSUE TITLE
Pointnet2_ops problem

### ISSUE THREAD

**Issue by husseinelamine** [AllenXiangX/SnowflakeNet#20]
there is an error while trying to install pointnet2_ops with python3.7 as you used 

nvcc fatal   : Unsupported gpu architecture 'compute_37'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    include_package_data=True,
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands       
    self.run_command(cmd)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command        
    cmd_obj.run()
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command        
    cmd_obj.run()
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command        
    cmd_obj.run()
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command        
    cmd_obj.run()
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 340, in run   
    self.build_extensions()
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 652, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\Husse\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

i tried to used python3.9 before and it worked but i had problem with chamfer_3D

installation didn't show any error but trying to run train.py showed an error that the module chamfer_3D could not be found

**Comment by husseinelamine** [comment]
well finally, it worked with python3.7 when i removed 3.7+PTX; from TORCH_CUDA_ARCH_LIST in pointnet2_ops setup.py (line 19)
