### ISSUE TITLE
Errors when training the completion models :1、raise self.exc_type(msg) ValueError: Caught ValueError in DataLoader worker process 0.    2、ValueError: high <= 0

### ISSUE THREAD

**Issue by by0619** [AllenXiangX/SnowflakeNet#28]
Dear sir, I am a beginner  tring to repeat your fantastic work. I made sure that the environment and PyTorch extensions are installed according to the instructions , then  I also modified  the dataset path in the [configuration files].But  when  training, I encountered these two problems.1、raise self.exc_type(msg) ValueError: Caught ValueError in DataLoader worker process 0.   
                                                                      2、ValueError: high <= 0
How  can I solve theses problems?Thanks and sincere regards!

(spd) ➜  [/home/carl/SnowflakeNet/completion] python train.py --config ./configs/pcn_cd1.yaml
Loaded compiled 3D CUDA chamfer distance
  0%|                                                                                                                                                                               | 0/906 [00:00<?, ?it/s][Open3D WARNING] Read PCD failed: unable to open file: /home/carl/SnowflakeNet/completion/train/partial/04530566/6c1458eec06ad0c147a67ad1fb1cf329/02.pcd
[Open3D WARNING] Read PCD failed: unable to open file: /home/carl/SnowflakeNet/completion/train/partial/04530566/df307c1941ca4bbd8f6810e1a2b6aa04/05.pcd
  0%|                                                                                                                                                                               | 0/906 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    train(config)
  File "train.py", line 91, in train
    for batch_idx, (taxonomy_ids, model_ids, data) in enumerate(t):
  File "/home/carl/anaconda3/envs/spd/lib/python3.7/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/carl/anaconda3/envs/spd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/carl/anaconda3/envs/spd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/carl/anaconda3/envs/spd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/carl/anaconda3/envs/spd/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/carl/anaconda3/envs/spd/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/carl/anaconda3/envs/spd/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/carl/anaconda3/envs/spd/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/carl/SnowflakeNet/completion/core/datasets/dataset.py", line 34, in __getitem__
    data = self.transforms(data)
  File "/home/carl/SnowflakeNet/completion/core/datasets/utils.py", line 71, in __call__
    data[k] = transform(v)
  File "/home/carl/SnowflakeNet/completion/core/datasets/utils.py", line 190, in __call__
    ptcloud = farthest_point_sample(ptcloud, n_valid)
  File "/home/carl/SnowflakeNet/completion/core/datasets/utils.py", line 33, in farthest_point_sample
    farthest = np.random.randint(0, N)
  File "mtrand.pyx", line 748, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1247, in numpy.random._bounded_integers._rand_int64
ValueError: high <= 0

**Comment by w1hao** [comment]
I had this problem as well and it has been resolved.
I just started using my previous dataset directly - the pointr dataset. However the test dataset path is not the same as required for this thesis.

**Comment by zzczzc-0118** [comment]
> 我也遇到过这个问题，现在已经解决了。我刚刚开始使用我以前的数据集 - pointr 数据集。但是，测试数据集路径与本论文所需的路径不同。
Hi, have you tested it yet? I would like to ask what is the path to the test dataset?
